export enum NodeName {
    Canvas = "canvas",
    Color = "color",
    Number = "number",
    Rectangle = "rectangle",
    Rotate = "rotate",
    Timer = "timer",
    Translate = "translate",
    IfElse = "if-else",
    String = "string",
    Split = "split",
    Operation = "operation",
    Log = "log",
    Arc = "arc",
    Check = "check",
    Boolean = "boolean",
    FunctionInputNode = "function-inputs",
    FunctionOutputNode = "function-outputs",
    FunctionCallNode = "function-call",
    ThreeJS = "threejs",
    ThreeJSBox = "threejs-box"
}